# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7gJ7q2tXoeXYoXSHfNPJwJzkX69y8BX
"""

import yfinance as yf
import pandas as pd
start_date = "2024-01-01"
end_date = "2024-06-30"
bse_csv_file = "/content/Equity.csv"
nse_csv_file = "/content/NSE Stocks.csv"
def fetch_and_save_bse_data(file_path):
    df = pd.read_csv(file_path)
    bse_data = df[df['Tickers'].str.endswith('.BO')][['Tickers', 'Security Id']].dropna()
    tickers_bse = bse_data['Tickers'].tolist()
    security_ids = bse_data['Security Id'].tolist()
    all_bse_data = pd.DataFrame()

    for ticker, sec_id in zip(tickers_bse, security_ids):
        try:
            stock_data = yf.download(ticker, start=start_date, end=end_date)
            if not stock_data.empty:
                stock_data = stock_data.T
                stock_data['Security Id'] = sec_id
                stock_data = stock_data[['Security Id'] + [col for col in stock_data.columns if col != 'Security Id']]
                all_bse_data = pd.concat([all_bse_data, stock_data], axis=0)
                print(f"Data for {ticker} ({sec_id}) fetched and appended.")
            else:
                print(f"No data available for {ticker}. Skipping.")
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
    all_bse_data.to_csv(f"BSE_Data_{start_date}_to_{end_date}.csv", index=False)
    print("BSE stock data has been saved to CSV.")
def fetch_and_save_nse_data(file_path):
    df = pd.read_csv(file_path)
    tickers_nse = df[df['Tickers'].str.endswith('.NS')]['Tickers'].dropna().tolist()
    all_nse_data = pd.DataFrame()

    for ticker in tickers_nse:
        try:
            stock_data = yf.download(ticker, start=start_date, end=end_date)
            if not stock_data.empty:
                stock_data = stock_data.T
                stock_data['Ticker'] = ticker
                stock_data = stock_data[['Ticker'] + [col for col in stock_data.columns if col != 'Ticker']]
                all_nse_data = pd.concat([all_nse_data, stock_data], axis=0)
                print(f"Data for {ticker} fetched and appended.")
            else:
                print(f"No data available for {ticker}. Skipping.")
        except Exception as e:
            print(f"Error fetching data for {ticker}: {e}")
    all_nse_data.to_csv(f"NSE_Data_{start_date}_to_{end_date}.csv", index=False)
    print("NSE stock data has been saved to CSV.")
fetch_and_save_bse_data(bse_csv_file)
fetch_and_save_nse_data(nse_csv_file)